config/routes.rb
Rails.application.routes.draw do
  
  get 'business/index'
  get 'business/goto'

  resources :channel_classes

  get 'spider_test' => 'spider#test'
  
  get 'admin/index'

  resources :goods

  resources :good_classes

  resources :topics

  resources :channels

  resources :activities, only: [:new, :create, :edit, :update, :destroy]
  get 'delete_activity' => 'activities#delete_activity' 
  get 'delete_micropost' => 'microposts#delete_micropost'

  resources :posts

  resources :categories

  get 'order/new'

  get 'order/create'

  mount WeixinRailsMiddleware::Engine, at: "/"
  resources :projects
 

  root 'static_pages#playmates'
  get 'playmates' => 'static_pages#playmates'
  get 'topics' => 'static_pages#topics'
  get 'activities' => 'static_pages#activities'
  get 'topics_of_category' => 'static_pages#topics_of_category'
  get 'admin' => 'admin#index'
  
  get 'show_channels' => 'static_pages#channels'
  get 'show_channel_classes' => 'static_pages#channel_classes'
  get 'delete_channel' => 'channels#destroy'
  get 'delete_channel_class' => 'channel_classes#destroy'
  get 'show_channels_of_class' => 'channels#show_channels_of_class'
  post 'search_channels' => 'channels#search_channels'
  post 'search_channel_classes' => 'channel_classes#search_channel_classes'
  get 'topics_of_channel' => 'channels#topics_of_channel'
  get 'to_publish_topic_of_channel' => 'channels#to_publish_topic_of_channel'
  get 'to_publish_topic_of_category' => 'categories#to_publish_topic_of_category'
  post 'publish_topic_of_channel' => 'channels#publish_topic_of_channel'
  post 'publish_topic_of_category' => 'categories#publish_topic_of_category'
  get 'to_upload_topic_pic' => 'channels#to_upload_topic_pic'
  get 'to_upload_topic_pic_weixin' => 'channels#to_upload_topic_pic_weixin'
  patch 'upload_topic_pics' => 'channels#upload_topic_pics'
  patch 'upload_topic_pics_weixin' => 'channels#upload_topic_pics_weixin'
  get 'delete_topic' => 'topics#delete_topic'
  post 'topic_like' => 'topics#like'
  post 'topic_unlike' => 'topics#unlike'
  get 'show_topic_likes' => 'topics#show_topic_likes'
  get 'topic_comments' => 'topics#topic_comments'
  get 'to_post_topic_comment' => 'topics#to_post_topic_comment'
  get 'delete_topic_comment' => 'topics#delete_comment'
  patch 'post_topic_comment' => 'topics#post_topic_comment'
  post 'topic_comment_like' => 'topics#comment_like'
  post 'topic_comment_unlike' => 'topics#comment_unlike'
  
  
  get 'to_upload_good_pic' => 'goods#to_upload_good_pic'
  get 'to_upload_good_pic_weixin' => 'goods#to_upload_good_pic_weixin'
  patch 'upload_good_pics' => 'goods#upload_good_pics'
  patch 'upload_good_pics_weixin' => 'goods#upload_good_pics_weixin'
  post 'good_like' => 'goods#like'
  post 'good_unlike' => 'goods#unlike'
  get 'show_good_likes' => 'goods#show_good_likes'
  get 'delete_good' => 'goods#delete_good'
  get 'good_comments' => 'goods#good_comments'
  get 'to_post_good_comment' => 'goods#to_post_good_comment'
  get 'delete_good_comment' => 'goods#delete_comment'
  patch 'post_good_comment' => 'goods#post_good_comment'
  
  
  get 'send_im_mgs' => 'users#send_im_mgs'
  get 'my_conversation_list' => 'users#my_conversation_list'
  
  get 'setup' => 'users#setup'
  get 'publish_message' => 'users#publish_message'
  get 'publish_activity' => 'activities#new'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'send_sms_code' => 'users#send_sms_code'
  post 'upload_mirco_pics' => 'users#upload_mirco_pics'
  get 'upload_msg_pic' => 'microposts#upload_msg_pic'
  get 'upload_msg_pic_weixin' => 'microposts#upload_msg_pic_weixin'
  
  get 'upload_activity_pic' => 'activities#upload_activity_pic'
  get 'upload_activity_pic_weixin' => 'activities#upload_activity_pic_weixin'
  patch 'upload_msg_pics' => 'microposts#upload_pics'
  patch 'upload_msg_pics_weixin' => 'microposts#upload_pics_weixin'
  post 'upload_activity_pics' => 'activities#upload_pics'
  post 'upload_activity_pics_weixin' => 'activities#upload_pics_weixin'
  post 'upload_user_avatar' => 'users#upload_user_avatar'
  post 'upload_user_avatar_weixin' => 'users#upload_user_avatar_weixin'
  get 'loading' => 'weixin_loading#show'
  post 'goto' => 'weixin_loading#goto'
  get 'myFunds' => 'projects#myFunds'
  get 'myProfile' => 'users#myProfile'
  get 'hisProfile' => 'users#hisProfile'
  get 'herProfile' => 'users#herProfile'
  get 'buy' => 'projects#buy'
  
  post 'like' => 'microposts#like'
  post 'unlike' => 'microposts#unlike'
  
  get 'post_comments' => 'microposts#post_comments'
  get 'activity_comments' => 'activities#activity_comments'
  patch 'post_comment' => 'microposts#post_comment'
  patch 'post_activity_comment' => 'activities#post_activity_comment'
  post 'leave_message' => 'users#leave_message'
  get 'leave_messages' => 'users#leave_messages'
  get 'to_post_comment' => 'microposts#to_post_comment'
  get 'to_activity_comment' => 'activities#to_activity_comment'
  get 'to_leave_message' => 'users#to_leave_message'
  delete 'logout' => 'sessions#destroy'
  
  get 'delete_comment' => 'microposts#delete_comment'
  get 'delete_activity_comment' => 'activities#delete_activity_comment'
  get 'delete_user_message' => 'users#delete_message'
  get 'show_post_likeds' => 'microposts#show_post_likeds'
  get 'show_activity_applies' => 'activities#show_activity_applies'
  get 'apply_activity' => 'activities#apply_activity'
  get 'cancel_activity_apply' => 'activities#cancel_activity_apply'
  
  get 'to_upload_user_avatar' => 'users#to_upload_user_avatar'
  get 'to_upload_user_avatar_weixin' => 'users#to_upload_user_avatar_weixin'
  
  resources :users , only: [:new, :create, :edit, :update,:myProfile]do
  end
  
  get 'show_photos' => 'users#show_photos'
  get 'update_user' => 'users#update_user'
  
  get 'posts_of_user' => 'users#posts_of_user'
  get 'activities_of_user' => 'users#activities_of_user'
  get 'activities_of_user_applied' => 'users#activities_of_user_applied'
  get 'topics_of_user' => 'users#topics_of_user'
  get 'topics_of_user_replied' => 'users#topics_of_user_replied'
  
  get 'privacy' => 'static_pages#privacy'
  get 'about_us' => 'static_pages#about_us'
  get 'agreement' => 'static_pages#agreement'
  
  get 'followings' => 'users#followings'
  get 'followers' => 'users#followers'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :orders, only: [:new,:create, :destroy]
  
  get 'weixin' => 'users#weixin_callback'
  
  get 'smscode' => 'sms_code#send_code'
  
  get 'test_upload' => 'static_pages#test_upload'
  
  post 'download_pic_from_weixin' => 'static_pages#download_pic_from_weixin'

  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :channel
  
  has_many :topic_pics, dependent: :destroy
  has_many :topic_comments, dependent: :destroy
  has_many :topic_likes, dependent: :destroy
  has_many :topic_reads, dependent: :destroy
  
  def like(like_user_id)
    topic_likes.create(user_id: like_user_id)
  end
  
  def unlike(like_user_id)
    topic_likes.find_by(user_id: like_user_id).destroy
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, only: [:destroy,:like,:unlike,:comment_like,:comment_unlike]
  before_action :logged_in_user ,except: [:index, :show, :topic_comments, :show_topic_likes,:like,:unlike,:comment_like,:comment_unlike]
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    # respond_to do |format|
    #   format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    redirect_to "/topics_of_channel?id=#{@topic.channel.id}"
  end


  def like
    @topic = Topic.find(params[:topicid])
    if current_user.nil?
      render text: "no_login"
    else
      @topic.like(current_user.id)
      render text: "liked"
    end
    
  end
  
  def unlike
    @topic = Topic.find(params[:topicid])
    if current_user.nil?
      render text: "no_login"
    else
      @topic.unlike(current_user.id)
      render text: "unliked"
    end
  end

  def comment_like
    @topic_comment = TopicComment.find(params[:commentid])
    if current_user.nil?
      render text: "no_login"
    else
      @topic_comment.like(current_user.id)
      render text: "liked"
    end
    
  end
  
  def comment_unlike
    @topic_comment = TopicComment.find(params[:commentid])
    if current_user.nil?
      render text: "no_login"
    else
      @topic_comment.unlike(current_user.id)
      render text: "unliked"
    end
  end


  def show_topic_likes
    @topic = Topic.find(params[:topic_id])
    @page_num = 0
    if params[:page_num]
      @page_num =  params[:page_num]
    end
    page_size = 5
    @total_page = ((@topic.topic_likes.count(:id).to_i - 1)/page_size )+1
    @likes = @topic.topic_likes.order("updated_at desc").limit(page_size).offset(@page_num.to_i * page_size.to_i)
    
    #fresh_when(etag: [@likes])
    Rails.logger.info "-----------------------page_num=#{@page_num}--------------------------------------"
    Rails.logger.info "-----------------------total_page=#{@total_page}--------------------------------------"
  end
  
  
  def delete_comment
    @topic_comment  = TopicComment.find(params[:id])
    @topic_comment.destroy
    flash[:success] = "删除成功！"
    redirect_to "/topic_comments?id=#{@topic_comment.topic.id}"
  end
  
  
  
  def topic_comments
    @topic = Topic.find(params[:id])
    
    if logged_in?
      @topic.topic_reads.create(:user_id => current_user.id)
    else
      @topic.topic_reads.create()
    end
    
    @page_num = 0
    if params[:page_num]
      @page_num =  params[:page_num]
    end
    page_size = 5
    @total_page = ((@topic.topic_comments.count(:id).to_i - 1)/page_size )+1
    @comments = @topic.topic_comments.order("updated_at desc").limit(page_size).offset(@page_num.to_i * page_size.to_i)
    
    Rails.logger.info "-----------------------page_num=#{@page_num}--------------------------------------"
    Rails.logger.info "-----------------------total_page=#{@total_page}--------------------------------------"
    
    @hot5_comments = @topic.topic_comments.sort_by {|comment| comment.topic_comment_likes.count}.reverse[0..4]
    Rails.logger.info "----------------------------------------------------@hot5_comments.count:#{@hot5_comments.count}"
    #fresh_when :etag => [@comments, @hot5_comments]
    
  end
  
  def to_post_topic_comment
    @topic = Topic.find(params[:topic_id])
    @is_reply = params[:reply]
    @comment_user = User.find(params[:to_user_id])
  end
  
  def post_topic_comment
    @topic = Topic.find(params[:topic_id])
    content = params[:content]
    @topic.topic_comments.create(:user_id => current_user.id, :content => content)
    #render 'post_comments'
    redirect_to "/topic_comments?id=#{@topic.id}"
  end
  
  
  def delete_topic
    @topic = Topic.find(params[:id])
    topic_type = @topic.topic_type
    @topic.destroy
    flash[:success] = "删除成功！"
    if topic_type == 'channel'
      redirect_to "/topics_of_channel?id=#{@topic.channel.id}"
    elsif topic_type == 'category'
      redirect_to "/topics_of_category?id=#{@topic.category.id}"
    else
      redirect_to "/topics_of_category"
    end
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_id, :category_id, :channel_id, :title, :content)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :channel_id %><br>
    <%= f.text_field :channel_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Category</th>
      <th>Channel</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.user %></td>
        <td><%= topic.category %></td>
        <td><%= topic.channel %></td>
        <td><%= topic.title %></td>
        <td><%= topic.content %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @topic.user %>
</p>

<p>
  <strong>Category:</strong>
  <%= @topic.category %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @topic.channel %>
</p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @topic.content %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

app/views/topics/show_topic_likes.html.erb
<%# cache @microposts do%>
<% @likes.each do |like|  %>
    <% liked_user = User.find(like.user_id)%>
    <% cache liked_user do%>
<div class="am-panel-bd" >
  
   <!-- 用户信息展示 -->
      <div class="am-g">
        <!--<div class="am-u-sm-2 am-u-lg-2">-->
        <!--  <span class="am-show-md-down">-->
        <!--    <img width="40" height="40" src="http://semantic-ui.com/images/avatar/large/jenny.jpg"/>-->
        <!--  </span>-->
        <!--  <span class="am-hide-md-down">-->
        <!--    <img width="80" height="80" src="http://semantic-ui.com/images/avatar/large/jenny.jpg"/>-->
        <!--  </span>-->
        <!--</div>-->
        <%= render :partial => "users/user_profile_display", :locals => { :user => liked_user,:time => like.updated_at } %>
      </div>
     
    </div>
<hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
    <% end%>
<% end%>

<!-- 分页 -->
<%#end%>

<%= render :partial => "shared/pagination",
:locals => { :total_page => @total_page,
             :page_num => @page_num,
             :pre_url => "/show_topic_likeds?topic_id=#{@topic.id}",
             :tips => '还没有人赞过，赶紧去点赞吧！' } %>

app/views/topics/to_post_topic_comment.html.erb
<style>
  .input_font {
    font-size: 1.2rem;
  }
  
  .input_font_small {
    font-size: 1rem;
  }
  
  select {
    font-size: 1.2rem;
  }
  
  select option {
    font-size: 1.2rem;
  }
</style>
<div class="am-panel am-panel-default">
  <%#=f orm_for(@user) do |f| %>


    <div class="am-panel-bd">
      <div class="am-g">
        <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">
          <h3>发表评论</h3>

          <%=form_for(@topic, html: {id: 'send_message' },url: post_topic_comment_url) do |f| %>
            <input type="hidden" id="topic_id" name="topic_id" value="<%= @topic.id%>" />
            <%=render 'shared/error_messages', object: f.object %>


              <div class="am-form-group">
                
                <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
                <textarea rows="8" class="am-form-field input_font" name="content" id="micropost_content" style="font-size:1.5rem;" >
                  <% if @is_reply=='1' %>
                    <%=p "回复 #{@comment_user.name} :\r\n "%>
                  <% end%>
                </textarea>
                <%#=f .text_area :description ,:rows=> '5' %>
              </div>

              <br>
              <div class="am-g">
                <!--<div class="am-u-sm-12 am-u-lg-12">-->
                <!--  <button type="button" class="am-btn am-btn-primary am-btn-block" onclick="return validate();" >上传图片</button>-->
                <!--</div>-->
                <div class="am-u-sm-6 am-u-lg-6">

                  <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="return validate();"> 发表</button>
                  </button>

                </div>


                <div class="am-u-sm-6 am-u-lg-6">
                  <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="goto('/activity_comments?id=<%= @topic.id%>')">取消</button>
                </div>
              </div>
              <% end %>

        </div>
      </div>
    </div>


</div>
<script>
  function validate() {
    //  show_alert($('#order_amount').val()%100);
    var micropost_content = $('#micropost_content').val().replace(/^\s+|\s+$/g, '');

    if (micropost_content == '') {
      show_alert("请写点什么吧！");
      return false;
    }
    else {
      document.getElementById("send_message").submit();
      //return true;
    }


  }
</script>