config/routes.rb
Rails.application.routes.draw do
  
  get 'business/index'
  get 'business/goto'

  resources :channel_classes

  get 'spider_test' => 'spider#test'
  
  get 'admin/index'

  resources :goods

  resources :good_classes

  resources :topics

  resources :channels

  resources :activities, only: [:new, :create, :edit, :update, :destroy]
  get 'delete_activity' => 'activities#delete_activity' 
  get 'delete_micropost' => 'microposts#delete_micropost'

  resources :posts

  resources :categories

  get 'order/new'

  get 'order/create'

  mount WeixinRailsMiddleware::Engine, at: "/"
  resources :projects
 

  root 'static_pages#playmates'
  get 'playmates' => 'static_pages#playmates'
  get 'topics' => 'static_pages#topics'
  get 'activities' => 'static_pages#activities'
  get 'topics_of_category' => 'static_pages#topics_of_category'
  get 'admin' => 'admin#index'
  
  get 'show_channels' => 'static_pages#channels'
  get 'show_channel_classes' => 'static_pages#channel_classes'
  get 'delete_channel' => 'channels#destroy'
  get 'delete_channel_class' => 'channel_classes#destroy'
  get 'show_channels_of_class' => 'channels#show_channels_of_class'
  post 'search_channels' => 'channels#search_channels'
  post 'search_channel_classes' => 'channel_classes#search_channel_classes'
  get 'topics_of_channel' => 'channels#topics_of_channel'
  get 'to_publish_topic_of_channel' => 'channels#to_publish_topic_of_channel'
  get 'to_publish_topic_of_category' => 'categories#to_publish_topic_of_category'
  post 'publish_topic_of_channel' => 'channels#publish_topic_of_channel'
  post 'publish_topic_of_category' => 'categories#publish_topic_of_category'
  get 'to_upload_topic_pic' => 'channels#to_upload_topic_pic'
  get 'to_upload_topic_pic_weixin' => 'channels#to_upload_topic_pic_weixin'
  patch 'upload_topic_pics' => 'channels#upload_topic_pics'
  patch 'upload_topic_pics_weixin' => 'channels#upload_topic_pics_weixin'
  get 'delete_topic' => 'topics#delete_topic'
  post 'topic_like' => 'topics#like'
  post 'topic_unlike' => 'topics#unlike'
  get 'show_topic_likes' => 'topics#show_topic_likes'
  get 'topic_comments' => 'topics#topic_comments'
  get 'to_post_topic_comment' => 'topics#to_post_topic_comment'
  get 'delete_topic_comment' => 'topics#delete_comment'
  patch 'post_topic_comment' => 'topics#post_topic_comment'
  post 'topic_comment_like' => 'topics#comment_like'
  post 'topic_comment_unlike' => 'topics#comment_unlike'
  
  
  get 'to_upload_good_pic' => 'goods#to_upload_good_pic'
  get 'to_upload_good_pic_weixin' => 'goods#to_upload_good_pic_weixin'
  patch 'upload_good_pics' => 'goods#upload_good_pics'
  patch 'upload_good_pics_weixin' => 'goods#upload_good_pics_weixin'
  post 'good_like' => 'goods#like'
  post 'good_unlike' => 'goods#unlike'
  get 'show_good_likes' => 'goods#show_good_likes'
  get 'delete_good' => 'goods#delete_good'
  get 'good_comments' => 'goods#good_comments'
  get 'to_post_good_comment' => 'goods#to_post_good_comment'
  get 'delete_good_comment' => 'goods#delete_comment'
  patch 'post_good_comment' => 'goods#post_good_comment'
  
  
  get 'send_im_mgs' => 'users#send_im_mgs'
  get 'my_conversation_list' => 'users#my_conversation_list'
  
  get 'setup' => 'users#setup'
  get 'publish_message' => 'users#publish_message'
  get 'publish_activity' => 'activities#new'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'send_sms_code' => 'users#send_sms_code'
  post 'upload_mirco_pics' => 'users#upload_mirco_pics'
  get 'upload_msg_pic' => 'microposts#upload_msg_pic'
  get 'upload_msg_pic_weixin' => 'microposts#upload_msg_pic_weixin'
  
  get 'upload_activity_pic' => 'activities#upload_activity_pic'
  get 'upload_activity_pic_weixin' => 'activities#upload_activity_pic_weixin'
  patch 'upload_msg_pics' => 'microposts#upload_pics'
  patch 'upload_msg_pics_weixin' => 'microposts#upload_pics_weixin'
  post 'upload_activity_pics' => 'activities#upload_pics'
  post 'upload_activity_pics_weixin' => 'activities#upload_pics_weixin'
  post 'upload_user_avatar' => 'users#upload_user_avatar'
  post 'upload_user_avatar_weixin' => 'users#upload_user_avatar_weixin'
  get 'loading' => 'weixin_loading#show'
  post 'goto' => 'weixin_loading#goto'
  get 'myFunds' => 'projects#myFunds'
  get 'myProfile' => 'users#myProfile'
  get 'hisProfile' => 'users#hisProfile'
  get 'herProfile' => 'users#herProfile'
  get 'buy' => 'projects#buy'
  
  post 'like' => 'microposts#like'
  post 'unlike' => 'microposts#unlike'
  
  get 'post_comments' => 'microposts#post_comments'
  get 'activity_comments' => 'activities#activity_comments'
  patch 'post_comment' => 'microposts#post_comment'
  patch 'post_activity_comment' => 'activities#post_activity_comment'
  post 'leave_message' => 'users#leave_message'
  get 'leave_messages' => 'users#leave_messages'
  get 'to_post_comment' => 'microposts#to_post_comment'
  get 'to_activity_comment' => 'activities#to_activity_comment'
  get 'to_leave_message' => 'users#to_leave_message'
  delete 'logout' => 'sessions#destroy'
  
  get 'delete_comment' => 'microposts#delete_comment'
  get 'delete_activity_comment' => 'activities#delete_activity_comment'
  get 'delete_user_message' => 'users#delete_message'
  get 'show_post_likeds' => 'microposts#show_post_likeds'
  get 'show_activity_applies' => 'activities#show_activity_applies'
  get 'apply_activity' => 'activities#apply_activity'
  get 'cancel_activity_apply' => 'activities#cancel_activity_apply'
  
  get 'to_upload_user_avatar' => 'users#to_upload_user_avatar'
  get 'to_upload_user_avatar_weixin' => 'users#to_upload_user_avatar_weixin'
  
  resources :users , only: [:new, :create, :edit, :update,:myProfile]do
  end
  
  get 'show_photos' => 'users#show_photos'
  get 'update_user' => 'users#update_user'
  
  get 'posts_of_user' => 'users#posts_of_user'
  get 'activities_of_user' => 'users#activities_of_user'
  get 'activities_of_user_applied' => 'users#activities_of_user_applied'
  get 'topics_of_user' => 'users#topics_of_user'
  get 'topics_of_user_replied' => 'users#topics_of_user_replied'
  
  get 'privacy' => 'static_pages#privacy'
  get 'about_us' => 'static_pages#about_us'
  get 'agreement' => 'static_pages#agreement'
  
  get 'followings' => 'users#followings'
  get 'followers' => 'users#followers'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :orders, only: [:new,:create, :destroy]
  
  get 'weixin' => 'users#weixin_callback'
  
  get 'smscode' => 'sms_code#send_code'
  
  get 'test_upload' => 'static_pages#test_upload'
  
  post 'download_pic_from_weixin' => 'static_pages#download_pic_from_weixin'

  

end

app/models/good.rb
class Good < ActiveRecord::Base
  belongs_to :user
  belongs_to :good_class
  
  has_many :good_pics, dependent: :destroy
  has_many :good_comments, dependent: :destroy
  has_many :good_likes, dependent: :destroy
  has_many :good_reads,dependent: :destroy
  
  
  def like(like_user_id)
    good_likes.create(user_id: like_user_id)
  end
  
  def unlike(like_user_id)
    good_likes.find_by(user_id: like_user_id).destroy
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, except: [:index,:show,:show_good_likes]
  skip_before_filter :verify_authenticity_token, only: [:destroy,:like,:unlike]
  # GET /goods
  # GET /goods.json
  def like
    @good = Good.find(params[:goodid])
    if current_user.nil?
      render text: "no_login"
    else
      @good.like(current_user.id)
      render text: "liked"
    end
    
  end
  
  def unlike
    @good = Good.find(params[:goodid])
    if current_user.nil?
      render text: "no_login"
    else
      @good.unlike(current_user.id)
      render text: "unliked"
    end
  end
  
  def delete_good
     @good = Good.find(params[:id])
     @good.destroy
     redirect_to "/goods"
  end

  def delete_comment
    @good_comment  = GoodComment.find(params[:id])
    @good_comment.destroy
    flash[:success] = "删除成功！"
    redirect_to "/good_comments?id=#{@good_comment.good.id}"
  end
  
  
  
  def good_comments
    @good = Good.find(params[:id])
    
    if logged_in?
      @good.good_reads.create(:user_id => current_user.id)
    else
      @good.good_reads.create()
    end
    
    @page_num = 0
    if params[:page_num]
      @page_num =  params[:page_num]
    end
    
    page_size = 5
    @total_page = ((@good.good_comments.count(:id).to_i - 1)/page_size )+1
    @comments = @good.good_comments.order("updated_at desc").limit(page_size).offset(@page_num.to_i * page_size.to_i)
    
    Rails.logger.info "-----------------------page_num=#{@page_num}--------------------------------------"
    Rails.logger.info "-----------------------total_page=#{@total_page}--------------------------------------"
    
    
  end
  
  def to_post_good_comment
    @good = Good.find(params[:good_id])
    @is_reply = params[:reply]
    @comment_user = User.find(params[:to_user_id])
  end
  
  def post_good_comment
    @good = Good.find(params[:good_id])
    content = params[:content]
    @good.good_comments.create(:user_id => current_user.id, :content => content)
    #render 'post_comments'
    redirect_to "/good_comments?id=#{@good.id}"
  end

  
  def show_good_likes
    @good = Good.find(params[:good_id])
    @page_num = 0
    if params[:page_num]
      @page_num =  params[:page_num]
    end
    page_size = 5
    @total_page = ((@good.good_likes.count(:id).to_i - 1)/page_size )+1
    @likes = @good.good_likes.order("updated_at desc").limit(page_size).offset(@page_num.to_i * page_size.to_i)
    
    #fresh_when(etag: [@likes])
    Rails.logger.info "-----------------------page_num=#{@page_num}--------------------------------------"
    Rails.logger.info "-----------------------total_page=#{@total_page}--------------------------------------"
  end
  
  def index
    # @goods = Good.all
    @page_num = 0
    if params[:page_num]
      @page_num =  params[:page_num]
    end
    page_size = 5
    @total_page = ((Good.count(:id).to_i - 1)/page_size )+1
    @tab_id = params[:id] || '0'
    
    #if @tab_id == '0'
      @goods = Good.order("updated_at desc").limit(page_size).offset(@page_num.to_i * page_size.to_i)
    #end
    
    # if @tab_id == '1'
    #   @microposts = Micropost.where( : => 'Ruby' ).order("updated_at").limit(page_size).offset(@page_num.to_i * page_size.to_i)
    # end
    
    Rails.logger.info "-----------------------page_num=#{@page_num}--------------------------------------"
    Rails.logger.info "-----------------------total_page=#{@total_page}--------------------------------------"
    
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    if @good.save
      if params[:if_completed] == 'yes'
          flash[:success] = "发布成功!"
          redirect_to "/goods"
       else
         #redirect_to "/upload_activity_pic?id=#{@activity.id}"
         @headers = env.select {|k,v| k.start_with? 'HTTP_'}
           .collect {|pair| [pair[0].sub(/^HTTP_/, ''), pair[1]]}
           .collect {|pair| pair.join(": ") << "<br>"}
           .sort
            if @headers.to_s.downcase.include?('micromessenger')
              redirect_to "/to_upload_good_pic_weixin?good_id=#{@good.id}"
            else
              redirect_to "/to_upload_good_pic?good_id=#{@good.id}"
            end
       end
    else
       flash[:success] = "发布失败，请重新发布!"
      render :new 
    end
    # respond_to do |format|
    #   if @good.save
    #     format.html { redirect_to @good, notice: 'Good was successfully created.' }
    #     format.json { render :show, status: :created, location: @good }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @good.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def to_upload_good_pic
    @good = Good.find(params[:good_id])
  end
  
  def to_upload_good_pic_weixin
    @good = Good.find(params[:good_id])
  end
  
  def upload_good_pics
     @good = Good.find(params[:good_id])
     if params[:files] && params[:files].any? 
        params[:files].each do |file|
        #@attachment = @micropost.message_pic.create!(:file => file)
        @attachment = @good.good_pics.new
        @attachment.file = file
        @attachment.save
        #@pic_urls += ",#{@attachment.file.url('400')}"
        end
     end
     
     #flash[:notice] = "您可以继续选择图片上传或者点击完成按钮"
     render 'to_upload_good_pic'
  end
  
  def upload_good_pics_weixin
    @good = Good.find(params[:good_id])
     
    access_token = get_access_token
    serverIds = params[:serverIds]
    if serverIds
      Rails.logger.info "-----------------------serverIds=#{serverIds}--------------------------------------"

      serverIds.split('||').each do |media_id|
        Rails.logger.info "---------------------media_id=#{media_id}--------------------------------------"

         file_name = get_file_from_wexin(access_token,media_id)
         file = File.new("#{file_name}")
         Rails.logger.info "---------------------file=#{file_name}--------------------------------------"

         @good.good_pics.create!(:file => file)
         File.delete("#{file_name}")
      end
    end
     #flash[:notice] = "您可以继续选择图片上传或者点击完成按钮"
     redirect_to "/to_upload_good_pic_weixin?good_id=#{@good.id}"
  end


    
  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:title, :description, :price, :original_price, :freight, :user_id, :good_class_id)
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/edit.html.erb
<h1>Editing Good</h1>

<%= render 'form' %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_path %>

app/views/goods/good_comments.html.erb
<%# cache @goods do%>
<style>
/*  .am-titlebar-hot .am-titlebar-title-hot:before {*/
/*  content: "";*/
/*  position: absolute;*/
/*  left: 2px;*/
/*  top: 8px;*/
/*  bottom: 8px;*/
/*  border-left: 3px solid #F3936A*/
  
/*}*/
/*.am-titlebar-default .am-titlebar-title:before {*/
/*  content: "";*/
/*  position: absolute;*/
/*  left: 2px;*/
/*  top: 8px;*/
/*  bottom: 8px;*/
/*  border-left: 3px solid #7177B5*/
/*}*/




</style>
<%= stylesheet_link_tag "http://cdn.bootcss.com/animate.css/3.4.0/animate.min.css"%>
<style>
  .liked{
    color:#DD514C;
  }
</style>
    <% cache @good do%>
<div class="am-panel am-panel-default" style="border:0;">
<div class="am-panel-bd" >
      
        <!-- 图片轮播 -->
      
      <%= cache @good.good_pics do%>
      
      <% if @good.good_pics.any?%>
      <div class="am-g" >
       
        
        <%= render :partial => "shared/pics_gallery", :locals => { :pics => @good.good_pics } %>
    
        
      </div>
      <% end%>
      
      <%end%>
      <br>
      <div class="am-g" >
        <div class="am-u-sm-6" align="left">
          <span style="font-size:1.5rem;color:#DD514C;">￥<%= @good.price%></span>
          <span style="font-size:1.2rem;"><del>￥<%= @good.original_price%></del></span>
        </div>
         <div class="am-u-sm-6" align="right">
          <span style="font-size:1.5rem;">浏览次数&nbsp;<%= @good.good_reads.count%></span>
        </div>
      </div>
      
      <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />

     <!-- 用户信息展示 -->
      <div class="am-g">
                <div class="am-u-sm-2">
            <% preurl = "hisProfile"%>
            <% pic_url = "http://threejed.b0.upaiyun.com/boy.jpg"%>
            <% if @good.user.sex == "女孩"%>
            <!--herProfile-->
            <% preurl = "herProfile"%>
            <% pic_url = "http://threejed.b0.upaiyun.com/girl.jpg"%>
            <% end%>
            <% if !@good.user.avatars.url.blank?%>
            
            <img class="am-circle" onclick="goto('/<%= preurl%>?id=<%= @good.user.id%>')" width="40" height="40" src="http://<%=@good.user.avatars.url("200")%>"/>
            <% else%>
            <img class="am-circle" onclick="goto('/<%= preurl%>?id=<%= @good.user.id%>')" width="40" height="40" src="<%= pic_url%>"/>
            <% end%>
        
         
        </div>
        <div class="am-u-sm-7">
          <div style="font-size: 1.5rem;"><strong><%= @good.user.name%></strong> </div>
              <div style="-webkit-font-smoothing: subpixel-antialiased; -moz-osx-font-smoothing: auto;font-size:1rem;">
                 <%= @good.user.province%> &nbsp;&nbsp;<%= @good.user.city%> &nbsp;&nbsp;<%= @good.user.district%>  
               </div>
          

        </div>
         <div class="am-u-sm-3 am-u-lg-3" >
            <div style="-webkit-font-smoothing: subpixel-antialiased; -moz-osx-font-smoothing: auto;font-size:1rem;">
               <%= time_ago_in_words_cn(@good.updated_at) %> 
               前
             </div>
            
        </div>
     
      </div>
      <br>
      
        
      <!-- 标题和描述展示-->
      
      <div class="am-g" >
        <div class="am-u-sm-12">
          
           <article  data-am-widget="paragraph"
           class="am-paragraph am-paragraph-default"
           style="font-size:1.2rem;"
           data-am-paragraph="{ tableScrollable: true, pureview: true }">
             <!--<hr data-am-widget="divider" style="color:#41BFB5;" class="am-divider am-divider-dotted" />-->
              <% if !@good.title.blank?%>
            <span style="color:#4A779D;font-size:1.6rem;">
              <%=@good.title  %>
            </span><br><br>
            <%end%>
            <%= @good.description%>
           </article>
        </div>
      </div>
      <br>
      
     
      
     
      <br>
     
     <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
      
      <!-- 留言和查看联系方式 -->
      <div class="am-g" align="center">
        <div class="am-u-sm-6 am-u-lg-6">
      		  <%= render :partial => "shared/contact_user", 
              :locals => { :content => "联系方式",:mobile => @good.user.mobile}  %>
      	</div>
      	<div class="am-u-sm-6 am-u-lg-6">
      		<button type="button" class="am-btn am-btn-primary am-radius am-btn-sm"
      		onclick="goto('/to_post_good_comment?good_id=<%= @good.id%>&to_user_id=<%=@good.user.id%>&reply=0')">
            <i class="am-icon-envelope"></i>&nbsp;&nbsp;
             给他留言
          </button>
      	</div>
      </div>
    <% end%>
</div>
</div>
<%#end%>




<!-- 全部评论列表区 -->
<div data-am-widget="titlebar" class="am-titlebar am-titlebar-default" >
      <h2 class="am-titlebar-title " style="font-size:1.6rem;color:#4A779D;">
      全部留言
      </h2>
</div> 
    
<% @comments.each do |comment| %>
  <% comment_user = User.find(comment.user_id)%>
  <% cache comment do%>
<div class="am-panel am-panel-default" style="border:0;">
  <div class="am-panel-bd">
        <div class="am-g">
            <div class="am-u-sm-2">
              <% preurl = "hisProfile"%>
              <% pic_url = "http://threejed.b0.upaiyun.com/boy.jpg"%>
              <% if comment_user.sex == "女孩"%>
              <!--herProfile-->
              <% preurl = "herProfile"%>
              <% pic_url = "http://threejed.b0.upaiyun.com/girl.jpg"%>
              <% end%>
              <% if !comment_user.avatars.url.blank?%>
              
              <img class="am-circle" onclick="goto('/<%= preurl%>?id=<%= comment_user.id%>')" width="40" height="40" src="http://<%=comment_user.avatars.url("200")%>"/>
              <% else%>
              <img class="am-circle" onclick="goto('/<%= preurl%>?id=<%= comment_user.id%>')" width="40" height="40" src="<%= pic_url%>"/>
              <% end%>
          
           
          </div>
          <div class="am-u-sm-7">
            
              <div style="font-size: 1.5rem;"><strong><%= comment_user.name%></strong> </div>
              <div style="-webkit-font-smoothing: subpixel-antialiased; -moz-osx-font-smoothing: auto;font-size:1rem;">
                 <%= comment_user.province%> &nbsp;&nbsp;<%= comment_user.city%> &nbsp;&nbsp;<%= comment_user.district%>  
               </div>
            
  
          </div>
           <div class="am-u-sm-3 am-u-lg-3" style="font-size:1rem;">
            <%= time_ago_in_words_cn(comment.updated_at) %> 
           前
          </div>
        </div>
        <br>
        <div class="am-g">
        <div class="am-u-sm-12 am-u-lg-12">
          
           <article class="am-show-md-down" data-am-widget="paragraph"
           class="am-paragraph am-paragraph-default"
           style="font-size:1.3rem;"
           data-am-paragraph="{ tableScrollable: true, pureview: true }">
            <%= raw(comment.content)%>
           </article>
           <article class="am-hide-md-down" data-am-widget="paragraph"
           class="am-paragraph am-paragraph-default"
           style="font-size:1.5rem;"
           data-am-paragraph="{ tableScrollable: true, pureview: true }">
            <%= raw(comment.content)%>
           </article>
        </div>
        </div>
        <br>
        <div class="am-g" >
         <div class="am-u-sm-12 am-u-lg-12" align="right">
           
          <button type="button"  
           class="am-btn am-btn-danger am-radius am-btn-xs"
           onclick="goto('/to_post_good_comment?good_id=<%= @good.id%>&to_user_id=<%=comment_user.id%>&reply=1')">
            回复
          </button>
           &nbsp;
           <%#= button_to '删除',delete_comment_path, method: :delete, data: { confirm: '确定删除吗?' } %>
           <% if logged_in? && (comment.user_id == current_user.id || @good.user.id == current_user.id)%>
           <%= link_to "删除", {action: 'delete_comment', id: comment.id}, {class: 'am-btn am-btn-danger am-radius am-btn-xs'} %>
           <% end %>
        </div>
        <br>
      </div>
        
    </div>
</div>
  <%end%>
<%end%>

<!-- 评论分页 -->

<%= render :partial => "shared/pagination",
:locals => { :total_page => @total_page,
             :page_num => @page_num,
             :pre_url => "/good_comments?id=#{@good.id}",
             :tips => '还没有人留言，赶紧去留言吧！' } %>
    

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @good.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @good.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @good.price %>
</p>

<p>
  <strong>Original price:</strong>
  <%= @good.original_price %>
</p>

<p>
  <strong>Freight:</strong>
  <%= @good.freight %>
</p>

<p>
  <strong>User:</strong>
  <%= @good.user %>
</p>

<p>
  <strong>Good class:</strong>
  <%= @good.good_class %>
</p>

<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_path %>

app/views/goods/to_post_good_comment.html.erb
<style>
  .input_font {
    font-size: 1.2rem;
  }
  
  .input_font_small {
    font-size: 1rem;
  }
  
  select {
    font-size: 1.2rem;
  }
  
  select option {
    font-size: 1.2rem;
  }
</style>
<div class="am-panel am-panel-default">
  <%#=f orm_for(@user) do |f| %>


    <div class="am-panel-bd">
      <div class="am-g">
        <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">
          <h3>留言</h3>

          <%=form_for(@good, html: {id: 'send_message' },url: post_good_comment_url) do |f| %>
            <input type="hidden" id="good_id" name="good_id" value="<%= @good.id%>" />
            <%=render 'shared/error_messages', object: f.object %>


              <div class="am-form-group">
                
                <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
                <textarea rows="8" class="am-form-field input_font" name="content" id="micropost_content" style="font-size:1.5rem;" >
                  <% if @is_reply=='1' %>
                    <%=p "回复 #{@comment_user.name} :\r\n "%>
                  <% end%>
                </textarea>
                <%#=f .text_area :description ,:rows=> '5' %>
              </div>

              <br>
              <div class="am-g">
                <!--<div class="am-u-sm-12 am-u-lg-12">-->
                <!--  <button type="button" class="am-btn am-btn-primary am-btn-block" onclick="return validate();" >上传图片</button>-->
                <!--</div>-->
                <div class="am-u-sm-6 am-u-lg-6">

                  <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="return validate();"> 发表</button>
                  </button>

                </div>


                <div class="am-u-sm-6 am-u-lg-6">
                  <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="goto('/good_comments?id=<%= @good.id%>')">取消</button>
                </div>
              </div>
              <% end %>

        </div>
      </div>
    </div>


</div>
<script>
  function validate() {
    //  show_alert($('#order_amount').val()%100);
    var micropost_content = $('#micropost_content').val().replace(/^\s+|\s+$/g, '');

    if (micropost_content == '') {
      show_alert("请写点什么吧！");
      return false;
    }
    else {
      document.getElementById("send_message").submit();
      //return true;
    }


  }
</script>