config/routes.rb
Rails.application.routes.draw do
  
  get 'business/index'
  get 'business/goto'

  resources :channel_classes

  get 'spider_test' => 'spider#test'
  
  get 'admin/index'

  resources :goods

  resources :good_classes

  resources :topics

  resources :channels

  resources :activities, only: [:new, :create, :edit, :update, :destroy]
  get 'delete_activity' => 'activities#delete_activity' 
  get 'delete_micropost' => 'microposts#delete_micropost'

  resources :posts

  resources :categories

  get 'order/new'

  get 'order/create'

  mount WeixinRailsMiddleware::Engine, at: "/"
  resources :projects
 

  root 'static_pages#playmates'
  get 'playmates' => 'static_pages#playmates'
  get 'topics' => 'static_pages#topics'
  get 'activities' => 'static_pages#activities'
  get 'topics_of_category' => 'static_pages#topics_of_category'
  get 'admin' => 'admin#index'
  
  get 'show_channels' => 'static_pages#channels'
  get 'show_channel_classes' => 'static_pages#channel_classes'
  get 'delete_channel' => 'channels#destroy'
  get 'delete_channel_class' => 'channel_classes#destroy'
  get 'show_channels_of_class' => 'channels#show_channels_of_class'
  post 'search_channels' => 'channels#search_channels'
  post 'search_channel_classes' => 'channel_classes#search_channel_classes'
  get 'topics_of_channel' => 'channels#topics_of_channel'
  get 'to_publish_topic_of_channel' => 'channels#to_publish_topic_of_channel'
  get 'to_publish_topic_of_category' => 'categories#to_publish_topic_of_category'
  post 'publish_topic_of_channel' => 'channels#publish_topic_of_channel'
  post 'publish_topic_of_category' => 'categories#publish_topic_of_category'
  get 'to_upload_topic_pic' => 'channels#to_upload_topic_pic'
  get 'to_upload_topic_pic_weixin' => 'channels#to_upload_topic_pic_weixin'
  patch 'upload_topic_pics' => 'channels#upload_topic_pics'
  patch 'upload_topic_pics_weixin' => 'channels#upload_topic_pics_weixin'
  get 'delete_topic' => 'topics#delete_topic'
  post 'topic_like' => 'topics#like'
  post 'topic_unlike' => 'topics#unlike'
  get 'show_topic_likes' => 'topics#show_topic_likes'
  get 'topic_comments' => 'topics#topic_comments'
  get 'to_post_topic_comment' => 'topics#to_post_topic_comment'
  get 'delete_topic_comment' => 'topics#delete_comment'
  patch 'post_topic_comment' => 'topics#post_topic_comment'
  post 'topic_comment_like' => 'topics#comment_like'
  post 'topic_comment_unlike' => 'topics#comment_unlike'
  
  
  get 'to_upload_good_pic' => 'goods#to_upload_good_pic'
  get 'to_upload_good_pic_weixin' => 'goods#to_upload_good_pic_weixin'
  patch 'upload_good_pics' => 'goods#upload_good_pics'
  patch 'upload_good_pics_weixin' => 'goods#upload_good_pics_weixin'
  post 'good_like' => 'goods#like'
  post 'good_unlike' => 'goods#unlike'
  get 'show_good_likes' => 'goods#show_good_likes'
  get 'delete_good' => 'goods#delete_good'
  get 'good_comments' => 'goods#good_comments'
  get 'to_post_good_comment' => 'goods#to_post_good_comment'
  get 'delete_good_comment' => 'goods#delete_comment'
  patch 'post_good_comment' => 'goods#post_good_comment'
  
  
  get 'send_im_mgs' => 'users#send_im_mgs'
  get 'my_conversation_list' => 'users#my_conversation_list'
  
  get 'setup' => 'users#setup'
  get 'publish_message' => 'users#publish_message'
  get 'publish_activity' => 'activities#new'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'send_sms_code' => 'users#send_sms_code'
  post 'upload_mirco_pics' => 'users#upload_mirco_pics'
  get 'upload_msg_pic' => 'microposts#upload_msg_pic'
  get 'upload_msg_pic_weixin' => 'microposts#upload_msg_pic_weixin'
  
  get 'upload_activity_pic' => 'activities#upload_activity_pic'
  get 'upload_activity_pic_weixin' => 'activities#upload_activity_pic_weixin'
  patch 'upload_msg_pics' => 'microposts#upload_pics'
  patch 'upload_msg_pics_weixin' => 'microposts#upload_pics_weixin'
  post 'upload_activity_pics' => 'activities#upload_pics'
  post 'upload_activity_pics_weixin' => 'activities#upload_pics_weixin'
  post 'upload_user_avatar' => 'users#upload_user_avatar'
  post 'upload_user_avatar_weixin' => 'users#upload_user_avatar_weixin'
  get 'loading' => 'weixin_loading#show'
  post 'goto' => 'weixin_loading#goto'
  get 'myFunds' => 'projects#myFunds'
  get 'myProfile' => 'users#myProfile'
  get 'hisProfile' => 'users#hisProfile'
  get 'herProfile' => 'users#herProfile'
  get 'buy' => 'projects#buy'
  
  post 'like' => 'microposts#like'
  post 'unlike' => 'microposts#unlike'
  
  get 'post_comments' => 'microposts#post_comments'
  get 'activity_comments' => 'activities#activity_comments'
  patch 'post_comment' => 'microposts#post_comment'
  patch 'post_activity_comment' => 'activities#post_activity_comment'
  post 'leave_message' => 'users#leave_message'
  get 'leave_messages' => 'users#leave_messages'
  get 'to_post_comment' => 'microposts#to_post_comment'
  get 'to_activity_comment' => 'activities#to_activity_comment'
  get 'to_leave_message' => 'users#to_leave_message'
  delete 'logout' => 'sessions#destroy'
  
  get 'delete_comment' => 'microposts#delete_comment'
  get 'delete_activity_comment' => 'activities#delete_activity_comment'
  get 'delete_user_message' => 'users#delete_message'
  get 'show_post_likeds' => 'microposts#show_post_likeds'
  get 'show_activity_applies' => 'activities#show_activity_applies'
  get 'apply_activity' => 'activities#apply_activity'
  get 'cancel_activity_apply' => 'activities#cancel_activity_apply'
  
  get 'to_upload_user_avatar' => 'users#to_upload_user_avatar'
  get 'to_upload_user_avatar_weixin' => 'users#to_upload_user_avatar_weixin'
  
  resources :users , only: [:new, :create, :edit, :update,:myProfile]do
  end
  
  get 'show_photos' => 'users#show_photos'
  get 'update_user' => 'users#update_user'
  
  get 'posts_of_user' => 'users#posts_of_user'
  get 'activities_of_user' => 'users#activities_of_user'
  get 'activities_of_user_applied' => 'users#activities_of_user_applied'
  get 'topics_of_user' => 'users#topics_of_user'
  get 'topics_of_user_replied' => 'users#topics_of_user_replied'
  
  get 'privacy' => 'static_pages#privacy'
  get 'about_us' => 'static_pages#about_us'
  get 'agreement' => 'static_pages#agreement'
  
  get 'followings' => 'users#followings'
  get 'followers' => 'users#followers'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :orders, only: [:new,:create, :destroy]
  
  get 'weixin' => 'users#weixin_callback'
  
  get 'smscode' => 'sms_code#send_code'
  
  get 'test_upload' => 'static_pages#test_upload'
  
  post 'download_pic_from_weixin' => 'static_pages#download_pic_from_weixin'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  # has_many :categories, class_name: "Category",
  #                           foreign_key: "parent_id",
  #                           dependent: :destroy
  has_many :posts
  has_many :topics
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :get_home_data
  before_action :logged_in_user,only: [:to_publish_topic_of_category]
  # GET /categories
  # GET /categories.json
  def index
    @my_categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def to_publish_topic_of_category
    @categories = Category.all
  end
  
  def publish_topic_of_category
    @category = Category.find(params[:category_id])
    @topic = @category.topics.build(:user_id => current_user.id,:content => params[:content],:topic_type => 'category',:title => params[:title])
     if @topic.save
       
      p '------------------发表成功!------------------------------'
       
      flash[:success] = "发表成功!"
      redirect_to "/topics_of_category?id=#{@category.id}"
     
       
     else
       flash[:danger] = "发表失败，请重新发布!"
       redirect_to '/to_publish_topic_of_category'
     end
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_topics_of_category.html.erb
<%# cache @topics do%>





<%= stylesheet_link_tag "http://cdn.bootcss.com/animate.css/3.4.0/animate.min.css"%>
<style>
  .liked{
    color:#DD514C;
  }
</style>
<% @topics.each do |topic| %>
    <% cache topic do%>
<div class="am-panel-bd" >
  
    <!-- 标题和描述展示-->
      
      <div class="am-g" >
        <div class="am-u-sm-12">
          
           <article  data-am-widget="paragraph"
           class="am-paragraph am-paragraph-default"
           style="font-size:1.3rem;"
           data-am-paragraph="{ tableScrollable: true, pureview: true }">
             <!--<hr data-am-widget="divider" style="color:#41BFB5;" class="am-divider am-divider-dotted" />-->
            <% if !topic.title.blank?%>
            <span style="color:#4A779D;font-size:1.6rem;" onclick="goto('/topic_comments?id=<%=topic.id%>')">
              <%=truncate(topic.title, :length => 25, :omission => '...')  %>
            </span><br>
            <%end%>
            <% preurl = "hisProfile"%>
            <% if topic.user.sex == "女孩"%>
            <% preurl = "herProfile"%>
            <% end%>
            <span style="font-size:1rem;" onclick="goto('/<%= preurl%>?id=<%= topic.user.id%>')"> 
            <font color="#4A779D"><%=topic.user.name%> </font>&nbsp; &nbsp;
            <%= time_ago_in_words_cn(topic.updated_at) %> 前
            </span>
            <br>           <br>            <br>
            <span onclick="goto('/topic_comments?id=<%=topic.id%>')">
              <%=truncate(topic.content, :length => 80, :omission => '...')  %>
            <span>
            <br><br>
            <div align="right" style="font-color:#F3936A;">
              <a href="/topic_comments?id=<%=topic.id%>">阅读原文-></a>
            </div>
            
           </article>
        </div>
      </div>
      <br>
      
      <hr data-am-widget="divider" style="" class="am-divider am-divider-dotted" />
      
      <!-- 评论和点赞 -->
      <div class="am-g" style="height: 15px;">
        <div class="am-u-sm-3" align="left" style="font-size:1.2rem;text-align:left">
         阅读(<%=topic.topic_reads.count%>)
           
        </div>
        <div class="am-u-sm-3" align="left" style="font-size:1.2rem;text-align:left">
         评论(<%=topic.topic_comments.count%>)
           
        </div>
        
        <div class="am-u-sm-3" style="font-size:1.3rem;" >
          
          <span class="am-icon-thumbs-up" id="like_<%=topic.id%>"
           onclick="like('like_<%=topic.id%>','<%= topic.id%>');">
            &nbsp;<%= topic.topic_likes.count%>
          </span> 
         
          
        </div>
        <div class="am-u-sm-3" style="font-size:1.3rem;" >
          <% delete_flag = '0'%>
          <% if !current_user.nil? && topic.user == current_user%>
          <% delete_flag = '1'%>
          <%end%>
         <span onclick="show_modal('/show_topic_likes?topic_id=<%=topic.id%>','<%= delete_flag%>','/delete_topic?id=<%=topic.id%>','topic')" 
         class="am-icon-ellipsis-h" 
         data-am-modal="{target: '#my-more'}"> &nbsp;更多</span>
          
        </div>
        
      </div>
 
    </div>
<hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
    <% end%>
<% end%>
<!--<hr data-am-widget="divider" style="" class="am-divider am-divider-default" />-->
<%#end%>

<!-- 分页 -->


<%= render :partial => "shared/pagination",
:locals => { :total_page => @total_page,
             :page_num => @page_num,
             :pre_url => "/topics_of_category?id=#{@tab_id}",
             :tips => "还没有人发帖，快去发帖吧"
            } %>


<!-- 底部按钮 -->
<div class="am-panel am-panel-default" style="border:0;">
    <div class="am-panel-bd">
        
        <div class="am-g" >
        <div class="am-u-sm-12 am-u-lg-12" align="center">
         
          <button type="button" 
                 class="am-btn am-btn-primary am-radius am-btn-sm am-btn-block"
                 onclick="goto('/to_publish_topic_of_category')">
             <span class="am-icon-comment-o" ></span>
            &nbsp;
             发&nbsp;&nbsp;&nbsp;帖
            </button>
           
        </div>
        <br>
      </div>
    </div>
</div>
<script>
  function like(id,topic_id){
    //show_alert(Number(obj.innerHTML));
    //var num = obj.innerHTML.replace(/&nbsp;/g,"") ;
    //show_alert(num);
    //obj.innerHTML = "&nbsp;&nbsp;"+ (Number(num)+1)
    //obj.addClass('animated bounceOutLeft');
    //obj.className = obj.className + "animated infinite bounceIn liked";
    $.ajax({
      method: "post",
      url: "topic_like",
      data: {topicid: topic_id}
      })
      .done(function( msg ) {
        //show_alert(msg);
        if(msg == 'no_login'){
            show_alert("请登录后再操作");
            window.location.href = "/login";
        }else{
          var num = $('#'+id).html().replace(/&nbsp;/g,"") ;
          $('#'+id).html("&nbsp;&nbsp;"+ (Number(num)+1));
          //show_alert($('#'+id).html());
          $('#'+id).addClass(' animated bounceIn liked').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function(){
            $(this).removeClass('animated bounceIn');
          });
          $('#'+id).attr("onclick","unlike('"+id+"','"+topic_id+"');");
        }
      });
  }
  
  function unlike(id,topic_id){
    //show_alert(Number(obj.innerHTML));
    //var num = obj.innerHTML.replace(/&nbsp;/g,"") ;
    //show_alert(num);
    //obj.innerHTML = "&nbsp;&nbsp;"+ (Number(num)+1)
    //obj.addClass('animated bounceOutLeft');
    //obj.className = obj.className + "animated infinite bounceIn liked";
    $.ajax({
      method: "post",
      url: "topic_unlike",
      data: { topicid: topic_id}
      })
      .done(function( msg ) {
        //show_alert(msg);
        if(msg == 'no_login'){
            show_alert("请登录后再操作");
            window.location.href = "/login";
        }else{
          var num = $('#'+id).html().replace(/&nbsp;/g,"") ;
          $('#'+id).html("&nbsp;&nbsp;"+ (Number(num)-1));
          //show_alert($('#'+id).html());
          $('#'+id).addClass(' animated bounceIn liked').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function(){
            $(this).removeClass('animated bounceIn liked');
          });
          $('#'+id).attr("onclick","like('"+id+"','"+topic_id+"');");
        }
      });
  }
</script>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
    <tr>
      <th>ID</th>
      <th>名称</th>
      <th>所属类别</th>
      <th colspan="3">操作</th>
    </tr>
    <tr>
     <% @my_categories.each do |category| %>
      <tr class="info">
         <td><%= category.id %></td>
        <td><%= category.name %></td>
        <%if Category.where(:id => category.parent_id).any?%>
        <td><%= Category.find(category.parent_id).name %></td>
        <%else%>
        <td></td>
        <% end%>
        <td><%= link_to '查看', category %></td>
        <td><%= link_to '编辑', edit_category_path(category) %></td>
        <td><%= link_to '删除', category, method: :delete, data: { confirm: '确定删除吗?' } %></td>
      </tr>
    <% end %>
    
    </tr>
  </table>

<br>

<button type="button" class="btn btn-info" onclick="goto('/categories/new')">新增分类</button>

<br><br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @category.parent_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/to_publish_topic_of_category.html.erb
<style>
  .input_font {
    font-size: 1.2rem;
  }
  
  .input_font_small {
    font-size: 1rem;
  }
  
  select {
    font-size: 1.2rem;
  }
  
  select option {
    font-size: 1.2rem;
  }
</style>
<div class="am-panel am-panel-default">
  <%#=f orm_for(@user) do |f| %>


    <div class="am-panel-bd">
      <div class="am-g">
        <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">
          <h3>我的想法</h3>
            <hr data-am-widget="divider" style="" class="am-divider am-divider-dashed" />

          

          <%=form_for(:category, html: {id: 'send_message' },url: publish_topic_of_category_url) do |f| %>
            
              <div class="am-form-group">
                
                <div class="am-input-group am-input-group-primary">
                  <span class="am-input-group-label input_font">标题&nbsp;:&nbsp;</span>
                  <input type="text" name="title" id="title" value="" placeholder="请输入标题(选填)" class="am-form-field input_font" required>
                </div>
                <br>
                <!--<hr data-am-widget="divider" style="" class="am-divider am-divider-default" />-->
                <textarea rows="8" class="am-form-field input_font" name="content" id="micropost_content" style="font-size:1.5rem;" placeholder="请输入内容(必填)"  ></textarea>
                
                <br>
                <div class="am-input-group am-input-group-primary">
                <span class="am-input-group-label input_font">板块&nbsp;:&nbsp;</span>
                 <select data-am-selected name="category_id" id="category_id" >
                  <% @categories.each do |category| %>
                  <option value="<%= category.id%>"><%= category.name%></option>
                  
                  <%end%>
                </select>
                </div>
                <%#=f .text_area :description ,:rows=> '5' %>
              </div>

              <br>
               <div class="am-g">
        <!--<div class="am-u-sm-12 am-u-lg-12">-->
        <!--  <button type="button" class="am-btn am-btn-primary am-btn-block" onclick="return validate();" >上传图片</button>-->
        <!--</div>-->
            <div class="am-u-sm-6 am-u-lg-6">
    
              <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="return validate();" >完成</button>
             
            </div>
            <!--<div class="am-u-sm-4 am-u-lg-4">-->
            <!--  <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="return validate('yes');" >完成</button>-->
            <!--</div>-->
            
            <div class="am-u-sm-6 am-u-lg-6">
              <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="goto('/topics_of_category')" >取消</button>
            </div>
          </div>
              <% end %>

        </div>
      </div>
    </div>


</div>
<script>
     function validate() {
      var micropost_content = $('#micropost_content').val().replace(/^\s+|\s+$/g, '');
      //alert(micropost_content)
        if(micropost_content == ''){
          show_alert("请写点什么吧！");
          return false;
        }else{
         // alert('111');
            document.getElementById("send_message").submit();
          //return true;
        }
       
     
  }
</script>