config/routes.rb
Rails.application.routes.draw do
  
  get 'business/index'
  get 'business/goto'

  resources :channel_classes

  get 'spider_test' => 'spider#test'
  
  get 'admin/index'

  resources :goods

  resources :good_classes

  resources :topics

  resources :channels

  resources :activities, only: [:new, :create, :edit, :update, :destroy]
  get 'delete_activity' => 'activities#delete_activity' 
  get 'delete_micropost' => 'microposts#delete_micropost'

  resources :posts

  resources :categories

  get 'order/new'

  get 'order/create'

  mount WeixinRailsMiddleware::Engine, at: "/"
  resources :projects
 

  root 'static_pages#playmates'
  get 'playmates' => 'static_pages#playmates'
  get 'topics' => 'static_pages#topics'
  get 'activities' => 'static_pages#activities'
  get 'topics_of_category' => 'static_pages#topics_of_category'
  get 'admin' => 'admin#index'
  
  get 'show_channels' => 'static_pages#channels'
  get 'show_channel_classes' => 'static_pages#channel_classes'
  get 'delete_channel' => 'channels#destroy'
  get 'delete_channel_class' => 'channel_classes#destroy'
  get 'show_channels_of_class' => 'channels#show_channels_of_class'
  post 'search_channels' => 'channels#search_channels'
  post 'search_channel_classes' => 'channel_classes#search_channel_classes'
  get 'topics_of_channel' => 'channels#topics_of_channel'
  get 'to_publish_topic_of_channel' => 'channels#to_publish_topic_of_channel'
  get 'to_publish_topic_of_category' => 'categories#to_publish_topic_of_category'
  post 'publish_topic_of_channel' => 'channels#publish_topic_of_channel'
  post 'publish_topic_of_category' => 'categories#publish_topic_of_category'
  get 'to_upload_topic_pic' => 'channels#to_upload_topic_pic'
  get 'to_upload_topic_pic_weixin' => 'channels#to_upload_topic_pic_weixin'
  patch 'upload_topic_pics' => 'channels#upload_topic_pics'
  patch 'upload_topic_pics_weixin' => 'channels#upload_topic_pics_weixin'
  get 'delete_topic' => 'topics#delete_topic'
  post 'topic_like' => 'topics#like'
  post 'topic_unlike' => 'topics#unlike'
  get 'show_topic_likes' => 'topics#show_topic_likes'
  get 'topic_comments' => 'topics#topic_comments'
  get 'to_post_topic_comment' => 'topics#to_post_topic_comment'
  get 'delete_topic_comment' => 'topics#delete_comment'
  patch 'post_topic_comment' => 'topics#post_topic_comment'
  post 'topic_comment_like' => 'topics#comment_like'
  post 'topic_comment_unlike' => 'topics#comment_unlike'
  
  
  get 'to_upload_good_pic' => 'goods#to_upload_good_pic'
  get 'to_upload_good_pic_weixin' => 'goods#to_upload_good_pic_weixin'
  patch 'upload_good_pics' => 'goods#upload_good_pics'
  patch 'upload_good_pics_weixin' => 'goods#upload_good_pics_weixin'
  post 'good_like' => 'goods#like'
  post 'good_unlike' => 'goods#unlike'
  get 'show_good_likes' => 'goods#show_good_likes'
  get 'delete_good' => 'goods#delete_good'
  get 'good_comments' => 'goods#good_comments'
  get 'to_post_good_comment' => 'goods#to_post_good_comment'
  get 'delete_good_comment' => 'goods#delete_comment'
  patch 'post_good_comment' => 'goods#post_good_comment'
  
  
  get 'send_im_mgs' => 'users#send_im_mgs'
  get 'my_conversation_list' => 'users#my_conversation_list'
  
  get 'setup' => 'users#setup'
  get 'publish_message' => 'users#publish_message'
  get 'publish_activity' => 'activities#new'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'send_sms_code' => 'users#send_sms_code'
  post 'upload_mirco_pics' => 'users#upload_mirco_pics'
  get 'upload_msg_pic' => 'microposts#upload_msg_pic'
  get 'upload_msg_pic_weixin' => 'microposts#upload_msg_pic_weixin'
  
  get 'upload_activity_pic' => 'activities#upload_activity_pic'
  get 'upload_activity_pic_weixin' => 'activities#upload_activity_pic_weixin'
  patch 'upload_msg_pics' => 'microposts#upload_pics'
  patch 'upload_msg_pics_weixin' => 'microposts#upload_pics_weixin'
  post 'upload_activity_pics' => 'activities#upload_pics'
  post 'upload_activity_pics_weixin' => 'activities#upload_pics_weixin'
  post 'upload_user_avatar' => 'users#upload_user_avatar'
  post 'upload_user_avatar_weixin' => 'users#upload_user_avatar_weixin'
  get 'loading' => 'weixin_loading#show'
  post 'goto' => 'weixin_loading#goto'
  get 'myFunds' => 'projects#myFunds'
  get 'myProfile' => 'users#myProfile'
  get 'hisProfile' => 'users#hisProfile'
  get 'herProfile' => 'users#herProfile'
  get 'buy' => 'projects#buy'
  
  post 'like' => 'microposts#like'
  post 'unlike' => 'microposts#unlike'
  
  get 'post_comments' => 'microposts#post_comments'
  get 'activity_comments' => 'activities#activity_comments'
  patch 'post_comment' => 'microposts#post_comment'
  patch 'post_activity_comment' => 'activities#post_activity_comment'
  post 'leave_message' => 'users#leave_message'
  get 'leave_messages' => 'users#leave_messages'
  get 'to_post_comment' => 'microposts#to_post_comment'
  get 'to_activity_comment' => 'activities#to_activity_comment'
  get 'to_leave_message' => 'users#to_leave_message'
  delete 'logout' => 'sessions#destroy'
  
  get 'delete_comment' => 'microposts#delete_comment'
  get 'delete_activity_comment' => 'activities#delete_activity_comment'
  get 'delete_user_message' => 'users#delete_message'
  get 'show_post_likeds' => 'microposts#show_post_likeds'
  get 'show_activity_applies' => 'activities#show_activity_applies'
  get 'apply_activity' => 'activities#apply_activity'
  get 'cancel_activity_apply' => 'activities#cancel_activity_apply'
  
  get 'to_upload_user_avatar' => 'users#to_upload_user_avatar'
  get 'to_upload_user_avatar_weixin' => 'users#to_upload_user_avatar_weixin'
  
  resources :users , only: [:new, :create, :edit, :update,:myProfile]do
  end
  
  get 'show_photos' => 'users#show_photos'
  get 'update_user' => 'users#update_user'
  
  get 'posts_of_user' => 'users#posts_of_user'
  get 'activities_of_user' => 'users#activities_of_user'
  get 'activities_of_user_applied' => 'users#activities_of_user_applied'
  get 'topics_of_user' => 'users#topics_of_user'
  get 'topics_of_user_replied' => 'users#topics_of_user_replied'
  
  get 'privacy' => 'static_pages#privacy'
  get 'about_us' => 'static_pages#about_us'
  get 'agreement' => 'static_pages#agreement'
  
  get 'followings' => 'users#followings'
  get 'followers' => 'users#followers'
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :orders, only: [:new,:create, :destroy]
  
  get 'weixin' => 'users#weixin_callback'
  
  get 'smscode' => 'sms_code#send_code'
  
  get 'test_upload' => 'static_pages#test_upload'
  
  post 'download_pic_from_weixin' => 'static_pages#download_pic_from_weixin'

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  has_many :activity_pics , dependent: :destroy
  has_many :activity_comments,dependent: :destroy
  has_many :activity_applies , dependent: :destroy
  #attr_accessor :id
  def apply(apply_user_id)
    activity_applies.create(:apply_user_id => apply_user_id)
  end
  
  def has_applied?(apply_user_id)
    apply = ActivityApply.find_by(:apply_user_id => apply_user_id,:activity_id => self.id)
    !apply.nil?
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user,except: [:activity_comments]
  skip_before_filter :verify_authenticity_token, only: [:destroy]
  before_action :correct_user, only: [:destroy, :delete_activity]
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    #@activity = Activity.new(activity_params)
    @activity = current_user.activities.build(activity_params)
    if @activity.save
      if params[:if_completed] == 'yes'
          flash[:success] = "发布成功!"
          redirect_to "/activities"
       else
         #redirect_to "/upload_activity_pic?id=#{@activity.id}"
         @headers = env.select {|k,v| k.start_with? 'HTTP_'}
           .collect {|pair| [pair[0].sub(/^HTTP_/, ''), pair[1]]}
           .collect {|pair| pair.join(": ") << "<br>"}
           .sort
            if @headers.to_s.downcase.include?('micromessenger')
              redirect_to "/upload_activity_pic_weixin?id=#{@activity.id}"
            else
              redirect_to "/upload_activity_pic?id=#{@activity.id}"
            end
       end
       
    else
      redirect_to '/activities/new'
    end
    # respond_to do |format|
    #   if @activity.save
    #     format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
    #     format.json { render :show, status: :created, location: @activity }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @activity.errors, status: :unprocessable_entity }
    #   end
    # end
  end


  def upload_activity_pic
    
    @activity = Activity.find(params[:id])
    #render 'upload_activity_pic'
  end
  
  def upload_activity_pic_weixin
    @activity = Activity.find(params[:id])
  end
  
  def test
    
  end
  
  def upload_pics
     
    @activity = Activity.find(params[:activity_id])
    
    if params[:files] && params[:files].any? 
        params[:files].each do |file|
        #@attachment = @micropost.message_pic.create!(:file => file)
        @activity.activity_pics.create!(:file => file)
        # @attachment = @activity.activity_pics.new
        # @attachment.file = file
        # @attachment.save
        #@pic_urls += ",#{@attachment.file.url('400')}"
        end
    end
   

     #flash[:notice] = "您可以继续选择图片上传或者点击完成按钮"
     render 'upload_activity_pic'
  end
  
  def upload_pics_weixin
    
    @activity = Activity.find(params[:activity_id])
    access_token = get_access_token
    serverIds = params[:serverIds]
    if serverIds
      Rails.logger.info "-----------------------serverIds=#{serverIds}--------------------------------------"

      serverIds.split('||').each do |media_id|
        Rails.logger.info "---------------------media_id=#{media_id}--------------------------------------"

         file_name = get_file_from_wexin(access_token,media_id)
         file = File.new("#{file_name}")
         Rails.logger.info "---------------------file=#{file_name}--------------------------------------"

         @activity.activity_pics.create!(:file => file)
         File.delete("#{file_name}")
      end
    end
    
    redirect_to "/upload_activity_pic_weixin?id=#{@activity.id}"
    
  end
  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def activity_comments
    @activity = Activity.find(params[:id])
    
    #@likeds = @micropost.likeds
    @page_num = 0
    if params[:page_num]
      @page_num =  params[:page_num]
    end
    page_size = 5
    @total_page = ((@activity.activity_comments.count(:id).to_i - 1)/page_size )+1
    @activity_comments = @activity.activity_comments.order("updated_at desc").limit(page_size).offset(@page_num.to_i * page_size.to_i)
    
    Rails.logger.info "-----------------------page_num=#{@page_num}--------------------------------------"
    Rails.logger.info "-----------------------total_page=#{@total_page}--------------------------------------"
    #fresh_when(etag: [@activity_comments])

  end
  
  def to_activity_comment
    @activity = Activity.find(params[:post_id])
    @is_reply = params[:reply]
    @comment_user = User.find(params[:to_user_id])
  end

  def post_activity_comment
    @activity = Activity.find(params[:post_id])
    content = params[:content]
    @activity.activity_comments.create(:post_user_id => current_user.id, :content => content)
    #render 'post_comments'
    redirect_to "/activity_comments?id=#{@activity.id}"
  end
  # DELETE /activities/1
  # DELETE /activities/1.json
  
  def delete_activity_comment
    
    @comment = ActivityComment.find(params[:id])
    @comment.destroy
    
    #flash[:success] = "Micropost deleted"
    #redirect_to request.referrer || root_url
    redirect_to "/activity_comments?id=#{@comment.activity.id}"
  end
  
  def show_activity_applies
     @activity = Activity.find(params[:post_id])
    #@likeds = @micropost.likeds
    @page_num = 0
    if params[:page_num]
      @page_num =  params[:page_num]
    end
    page_size = 5
    @total_page = ((@activity.activity_applies.count(:id).to_i - 1)/page_size )+1
    @activity_applies = @activity.activity_applies.order("updated_at desc").limit(page_size).offset(@page_num.to_i * page_size.to_i)
    
    Rails.logger.info "-----------------------page_num=#{@page_num}--------------------------------------"
    Rails.logger.info "-----------------------total_page=#{@total_page}--------------------------------------"
    #fresh_when(etag: [@activity_applies])
  end
  
  def apply_activity
    @activity = Activity.find(params[:activity_id])
  
    if @activity.has_applied?(current_user.id)
      flash[:success] = "您已经报过名!"
    elsif @activity.user == current_user
      flash[:success] = "这是您发布的活动，不需要报名!"
    else
      @activity.apply(current_user.id)
      flash[:success] = "报名成功!"
    end
    
    redirect_to "/activity_comments?id=#{@activity.id}"
  end
  
  def cancel_activity_apply
    apply = ActivityApply.find(params[:apply_id])
    apply.destroy
    flash[:success] = "取消报名成功!"
    redirect_to "/activity_comments?id=#{apply.activity.id}"
  end
  
  def delete_activity
    #@activity = Activity.find(params[:id])
    @activity.destroy
    flash[:success] = "删除成功！"
    redirect_to '/activities'
  end
  
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: '' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :description, :starttime, :endtime, :place, :number_of_people, :pay_type, :average_cost, :user_id, :tags, :apply_up_limit)
    end
    
    def correct_user
      @activity = current_user.activities.find_by(id: params[:id])
      redirect_to root_url if @activity.nil?
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_user_activities.html.erb
<%# cache @activities do%>





<%= stylesheet_link_tag "http://cdn.bootcss.com/animate.css/3.4.0/animate.min.css"%>
<style>
  .liked{
    color:#DD514C;
  }
</style>
<% @activities.each do |activity| %>
    <% cache activity do%>
    <div class="am-panel am-panel-default" style="border:0.5;">
      <div class="am-panel-bd" >
  
   <!-- 用户信息展示 -->
      <div class="am-g">
        <!--<div class="am-u-sm-2 am-u-lg-2">-->
        <!--  <span class="am-show-md-down">-->
        <!--    <img width="40" height="40" src="http://semantic-ui.com/images/avatar/large/jenny.jpg"/>-->
        <!--  </span>-->
        <!--  <span class="am-hide-md-down">-->
        <!--    <img width="80" height="80" src="http://semantic-ui.com/images/avatar/large/jenny.jpg"/>-->
        <!--  </span>-->
        <!--</div>-->
        
        
        <%= render :partial => "users/user_profile_display", :locals => { :user => activity.user,:time => activity.created_at } %>
    
        
      </div>
      <br>
  
      <!-- 图片轮播 -->
      
      <%= cache activity.activity_pics do%>
      
      <% if activity.activity_pics.any?%>
      <div class="am-g" >
       
        
        <%= render :partial => "shared/pics_gallery", :locals => { :pics => activity.activity_pics } %>
    
        
      </div>
      <% end%>
      
      <%end%>
      
     
      <br>
      
      <!-- 标题和描述展示-->
      
      <div class="am-g" >
        <div class="am-u-sm-12" onclick="goto('/activity_comments?id=<%= activity.id%>')">
          
           <article  data-am-widget="paragraph"
           class="am-paragraph am-paragraph-default"
           style="font-size:1.3rem;"
           data-am-paragraph="{ tableScrollable: true, pureview: true }">
            <h2><font color="#D7342E"><%= activity.title%></font></h2>
             <hr data-am-widget="divider" style="color:#41BFB5;" class="am-divider am-divider-dotted" />
            <%= activity.description%>
           </article>
        </div>
      </div>
      <br>
      <hr data-am-widget="divider" style="" class="am-divider am-divider-dotted" />
      
      <!-- 评论和点赞 -->
      <div class="am-g" align="center">
        <div class="am-u-sm-4" >
          <span class="am-icon-comments-o" 
          onclick="goto('/activity_comments?id=<%= activity.id%>')">
            &nbsp;<%= activity.activity_comments.count%></span> 
            
        </div>
        <div class="am-u-sm-4" >
          
          <span class="am-icon-user" id="like_<%=activity.id%>"
           onclick="goto('/activity_comments?id=<%= activity.id%>')">
            &nbsp;<%= activity.activity_applies.count%>
          </span> 
         
          
        </div>
        <div class=" am-u-sm-4" >
          <% delete_flag = '0'%>
          <% if !current_user.nil? && activity.user == current_user%>
          <% delete_flag = '1'%>
          <%end%>
         <span onclick="show_modal('/show_activity_applies?post_id=<%=activity.id%>','<%= delete_flag%>','/delete_activity?id=<%=activity.id%>','activity')" 
         class="am-icon-ellipsis-h" style="font-size:1.3rem;" 
         data-am-modal="{target: '#my-more'}"> &nbsp;更多</span>
          
        </div>
        
      </div>
 
    </div>
    </div>
    <% end%>
<% end%>

<%#end%>

<!-- 分页 -->


<%= render :partial => "shared/pagination",
:locals => { :total_page => @total_page,
             :page_num => @page_num,
             :pre_url => pre_url,
             :tips => tips
            } %>

<script>
  function like(id,activity_id,user_id){
    //show_alert(Number(obj.innerHTML));
    //var num = obj.innerHTML.replace(/&nbsp;/g,"") ;
    //show_alert(num);
    //obj.innerHTML = "&nbsp;&nbsp;"+ (Number(num)+1)
    //obj.addClass('animated bounceOutLeft');
    //obj.className = obj.className + "animated infinite bounceIn liked";
    $.ajax({
      method: "activity",
      url: "like",
      data: {activityid: activity_id, to_user_id: user_id}
      })
      .done(function( msg ) {
        //show_alert(msg);
        if(msg == 'no_login'){
            show_alert("请登录后再操作");
            window.location.href = "/login";
        }else{
          var num = $('#'+id).html().replace(/&nbsp;/g,"") ;
          $('#'+id).html("&nbsp;&nbsp;"+ (Number(num)+1));
          //show_alert($('#'+id).html());
          $('#'+id).addClass(' animated bounceIn liked').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function(){
            $(this).removeClass('animated bounceIn');
          });
          $('#'+id).attr("onclick","unlike('"+id+"','"+activity_id+"','"+user_id+"');");
        }
      });
  }
  
  function unlike(id,activity_id,user_id){
    //show_alert(Number(obj.innerHTML));
    //var num = obj.innerHTML.replace(/&nbsp;/g,"") ;
    //show_alert(num);
    //obj.innerHTML = "&nbsp;&nbsp;"+ (Number(num)+1)
    //obj.addClass('animated bounceOutLeft');
    //obj.className = obj.className + "animated infinite bounceIn liked";
    $.ajax({
      method: "activity",
      url: "unlike",
      data: { activityid: activity_id,to_user_id: user_id}
      })
      .done(function( msg ) {
        //show_alert(msg);
        if(msg == 'no_login'){
            show_alert("请登录后再操作");
            window.location.href = "/login";
        }else{
          var num = $('#'+id).html().replace(/&nbsp;/g,"") ;
          $('#'+id).html("&nbsp;&nbsp;"+ (Number(num)-1));
          //show_alert($('#'+id).html());
          $('#'+id).addClass(' animated bounceIn liked').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function(){
            $(this).removeClass('animated bounceIn liked');
          });
          $('#'+id).attr("onclick","like('"+id+"','"+activity_id+"','"+user_id+"');");
        }
      });
  }
</script>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Place</th>
      <th>Number of people</th>
      <th>Pay type</th>
      <th>Average cost</th>
      <th>User</th>
      <th>Tags</th>
      <th>Apply up limit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.title %></td>
        <td><%= activity.description %></td>
        <td><%= activity.starttime %></td>
        <td><%= activity.endtime %></td>
        <td><%= activity.place %></td>
        <td><%= activity.number_of_people %></td>
        <td><%= activity.pay_type %></td>
        <td><%= activity.average_cost %></td>
        <td><%= activity.user %></td>
        <td><%= activity.tags %></td>
        <td><%= activity.apply_up_limit %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<!--<h1>New Activity</h1>-->

<%= render 'form' %>

<%#= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @activity.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @activity.starttime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @activity.endtime %>
</p>

<p>
  <strong>Place:</strong>
  <%= @activity.place %>
</p>

<p>
  <strong>Number of people:</strong>
  <%= @activity.number_of_people %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @activity.pay_type %>
</p>

<p>
  <strong>Average cost:</strong>
  <%= @activity.average_cost %>
</p>

<p>
  <strong>User:</strong>
  <%= @activity.user %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @activity.tags %>
</p>

<p>
  <strong>Apply up limit:</strong>
  <%= @activity.apply_up_limit %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/activities/show_activity_applies.html.erb
<%# cache @microposts do%>

<%= stylesheet_link_tag "http://cdn.bootcss.com/animate.css/3.4.0/animate.min.css"%>
<style>
  .applyd{
    color:#DD514C;
  }
</style>
<% @activity_applies.each do |apply|  %>
    <% applyd_user = User.find(apply.apply_user_id)%>
    <% cache applyd_user do%>
<div class="am-panel-bd" >
  
   <!-- 用户信息展示 -->
      <div class="am-g">
        <%= render :partial => "users/user_profile_display", :locals => { :user => applyd_user,:time => apply.created_at } %>
      </div>
     
    </div>
<hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
    <% end%>
<% end%>

<%#end%>
<!-- 分页 -->


<%= render :partial => "shared/pagination",
:locals => { :total_page => @total_page,
             :page_num => @page_num,
             :pre_url => "/show_activity_applies?post_id=#{@activity.id}",
             :tips => '还没有人报名，赶紧去报名吧！' } %>

app/views/activities/to_activity_comment.html.erb
<style>
  .input_font {
    font-size: 1.2rem;
  }
  
  .input_font_small {
    font-size: 1rem;
  }
  
  select {
    font-size: 1.2rem;
  }
  
  select option {
    font-size: 1.2rem;
  }
</style>
<div class="am-panel am-panel-default">
  <%#=f orm_for(@user) do |f| %>


    <div class="am-panel-bd">
      <div class="am-g">
        <div class="am-u-lg-6 am-u-md-8 am-u-sm-centered">
          <h3>发表评论</h3>
          <hr>

          <br>

          <%=form_for(@activity, html: {id: 'send_message' },url: post_activity_comment_url) do |f| %>
            <input type="hidden" id="post_id" name="post_id" value="<%= @activity.id%>" />
            <%=render 'shared/error_messages', object: f.object %>


              <div class="am-form-group">
                
                <hr data-am-widget="divider" style="" class="am-divider am-divider-default" />
                <textarea rows="8" class="am-form-field input_font" name="content" id="micropost_content" style="font-size:1.5rem;" >
                  <% if @is_reply=='1' %>
                    <%=p "回复 #{@comment_user.name} :\r\n "%>
                  <% end%>
                </textarea>
                <%#=f .text_area :description ,:rows=> '5' %>
              </div>

              <br>
              <div class="am-g">
                <!--<div class="am-u-sm-12 am-u-lg-12">-->
                <!--  <button type="button" class="am-btn am-btn-primary am-btn-block" onclick="return validate();" >上传图片</button>-->
                <!--</div>-->
                <div class="am-u-sm-6 am-u-lg-6">

                  <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="return validate();"> 发表</button>
                  </button>

                </div>


                <div class="am-u-sm-6 am-u-lg-6">
                  <button type="button" class="am-btn am-btn-primary am-btn-block am-btn-sm am-radius" onclick="goto('/activity_comments?id=<%= @activity.id%>')">取消</button>
                </div>
              </div>
              <% end %>

        </div>
      </div>
    </div>


</div>
<script>
  function validate() {
    //  show_alert($('#order_amount').val()%100);
    var micropost_content = $('#micropost_content').val().replace(/^\s+|\s+$/g, '');

    if (micropost_content == '') {
      show_alert("请写点什么吧！");
      return false;
    }
    else {
      document.getElementById("send_message").submit();
      //return true;
    }


  }
</script>